baseURL = 'https://zoybzo.github.io/'
# languageCode = 'en-us'
languageCode = 'zh-cn'
title = "Zoybzo's Site"
theme = "papermod"
pagination.pagerSize = 10

enableInlineShortcodes = true
enableEmoji = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

defaultContentLanguage = 'zh' # æœ€é¡¶éƒ¨é¦–å…ˆå±•ç¤ºçš„è¯­è¨€é¡µé¢
# defaultContentLanguageInSubdir = true

[minify]
disableXML = true

[languages.zh]
languageName = "Chinese"
weight = 1

  [languages.zh.taxonomies]
  category = "Category"
  tag = "Label"
  series = "Series"

[[languages.zh.menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[languages.zh.menu.main]]
name = "Search"
url = "search"
weight = 10

[[languages.zh.menu.main]]
name = "Tags"
url = "tags"
weight = 10

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
defaultTheme = "auto"
ShowCodeCopyButtons = true
ShowWordCounts = true
VisitCount = true
ShowAllPagesInArchive = true
DateFormat = "2006-01-02"
ShowPostNavLinks = true
ShowPageNums = true
ShowLastMod = true
ShowToc = true
TocOpen = true
comments = true
mainSections = [ "papers", "posts" ]

  [params.homeInfoParams]
  Title = "Hi! ğŸ‘‹"
  Content = """
  ä½ å¥½ï¼Œè¿™æ˜¯ Zoybzo çš„ä¸ªäººåšå®¢ï¼Œæˆ‘ä¼šåœ¨è¿™é‡Œè®°å½•ä¸€äº›æŠ€æœ¯ç›¸å…³çš„å†…å®¹ï¼Œå¸Œæœ›å¯¹ä½ æœ‰ç”¨ï¼
  """

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/zoybzo"
